version: '3.1'

services:
  locator:
    build: ./Locator-service
    volumes:
      - ./data:/app/data
    ports:
      - 7000:7000

  dummy:
    build: ./Dummy-service
    ports:
      - 7001:7001

  store:
    build: ./Store-service
    ports:
      - 7002:7002