version: '3.1'

services:
  locator:
    build: ./Locator-service
    volumes:
      - ./Locator-service/internal/repository:/app/Locator-service/internal/repository
    ports:
      - 7000:7000

  dummy:
    build: ./Dummy-service
    ports:
      - 7001:7001
